### ISSUE TITLE
What does the language switcher look like?

### ISSUE THREAD

**Issue by hwhsu1231** [crowdin/translate-readme#40]
Hello, Author.

I wonder what does the language switcher this GitHub Aciton generate for us look like?

Can you take a screenshot for us to take a look?

**Comment by Natalia936** [comment]
Dear @hwhsu1231 , let u double-check everything and come back to you

**Comment by andrii-bodnar** [comment]
Hi @hwhsu1231, you can check the example here - https://github.com/andrii-bodnar/translate-readme-demo. PR - #1
